local o = vim.opt

o.number = true
o.numberwidth = 1
o.relativenumber = true
o.title = true
o.winminheight = 0
o.winminwidth = 0
o.expandtab = true
o.cindent = true
o.smartindent = true
o.wrap = false
o.smartcase = true
o.cursorline = true
o.termguicolors = true
o.splitright = true
o.splitbelow = true
o.mousemodel = "extend"
o.swapfile = false
o.fileformats = 'dos'
o.foldmethod = "indent"
o.foldlevel = 99
o.signcolumn = "auto:9"
-- o.updatetime = 0
-- o.background = "dark" -- 耗时高
-- o.backspace = "indent,eol,start"
-- o.iskeyword = '@,48-57,_,192-255'
-- o.autoindent = true -- true
